// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
// Edit this file, as it is a specific handler function for your service

package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

func Index(lzr *i18n.Localizer, title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"row justify-content-center mt-4\"><div class=\"col-md-8 text-center mb-5\"><i class=\"bi bi-building display-1 text-primary\"></i><h1 class=\"mt-3 fw-bold\">Willkommen im OZG-Bürgerportal</h1><p class=\"lead text-muted\">Stellen Sie Ihre Anträge einfach, sicher und vollständig digital. Ihr Antrag wird direkt an die zuständige Behörde weitergeleitet.</p></div></div><div class=\"row justify-content-center g-4\"><div class=\"col-md-4\"><div class=\"card h-100 shadow-sm border-0\"><div class=\"card-body text-center p-4\"><i class=\"bi bi-file-earmark-plus display-4 text-primary mb-3\"></i><h5 class=\"fw-bold\">Neuen Antrag stellen</h5><p class=\"text-muted small\">Füllen Sie ein Formular aus und reichen Sie Ihren Antrag digital ein.</p><a href=\"/baumfaellung\" class=\"btn btn-primary mt-2\"><i class=\"bi bi-arrow-right me-1\"></i>Antrag stellen</a></div></div></div><div class=\"col-md-4\"><div class=\"card h-100 shadow-sm border-0\"><div class=\"card-body text-center p-4\"><i class=\"bi bi-list-ul display-4 text-primary mb-3\"></i><h5 class=\"fw-bold\">Meine Anträge</h5><p class=\"text-muted small\">Sehen Sie den Status Ihrer eingereichten Anträge ein.</p><a href=\"#\" class=\"btn btn-outline-primary mt-2\"><i class=\"bi bi-arrow-right me-1\"></i>Anträge anzeigen</a></div></div></div><div class=\"col-md-4\"><div class=\"card h-100 shadow-sm border-0\"><div class=\"card-body text-center p-4\"><i class=\"bi bi-person-circle display-4 text-primary mb-3\"></i><h5 class=\"fw-bold\">Mein Konto</h5><p class=\"text-muted small\">Verwalten Sie Ihr Profil und Ihre Sicherheitseinstellungen.</p><a href=\"#\" class=\"btn btn-outline-primary mt-2\"><i class=\"bi bi-arrow-right me-1\"></i>Zum Profil</a></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("OZG-Bürgerportal", "").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
