// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TOTPVerify() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"card shadow-sm\"><div class=\"card-header bg-primary text-white\"><h4 class=\"mb-0\"><i class=\"bi bi-shield-check me-2\"></i>2-Faktor Bestätigung</h4></div><div class=\"card-body text-center\"><p class=\"text-muted mb-4\">Bitte gib den aktuellen Code aus deiner Authenticator App ein.</p><form hx-post=\"/auth/login/totp\" hx-target=\"#result\" hx-swap=\"innerHTML\"><div class=\"mb-3 text-start\"><label for=\"totp_code\" class=\"form-label fw-bold\">6-stelliger Code<span class=\"text-danger\">*</span></label> <input type=\"text\" id=\"totp_code\" name=\"totp_code\" class=\"form-control form-control-lg text-center\" placeholder=\"123456\" maxlength=\"6\" autocomplete=\"one-time-code\" required></div><div class=\"d-grid mt-4\"><button type=\"submit\" class=\"btn btn-primary btn-lg\"><i class=\"bi bi-unlock me-2\"></i>Anmelden</button></div></form><div id=\"result\" class=\"mt-3\"></div><div class=\"mt-3\"><a href=\"/auth/login\" class=\"text-muted small\"><i class=\"bi bi-arrow-left me-1\"></i>Zurück zum Login</a></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("2-Faktor Bestätigung", "").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
