// Don't edit this file, as it is generated by dredger
// TODO: use wire for dependencies

package main

import (
	"antragservice7/core"
	"antragservice7/core/log"
	"antragservice7/core/tracing"
	"antragservice7/db"
	"antragservice7/rest"
	"antragservice7/rest/middleware"
	"embed"
	"net/http"
	"os/signal"
	"syscall"

	"antragservice7/web"
	"context"
	"crypto/tls"
	_ "embed"
	"flag"
	"os"

	"github.com/labstack/echo-contrib/v5/echoprometheus"
	"github.com/labstack/echo/v5"
	// "go.opentelemetry.io/contrib/instrumentation/github.com/labstack/echo/otelecho"
)

//go:embed web
var embeddedFS embed.FS

func main() {
	// Create contexts (for shutdown)
	echoCtx, echoCancel := context.WithCancel(context.Background()) // context only for echo
	defer echoCancel()                                              // cancel echo when main ends (should not happen, just in case)
	ctx, cancel := context.WithCancel(context.Background())         // context for everything else
	defer cancel()                                                  // cancel everything when main ends
	// Create shutdown listener
	go func() {
		sig := make(chan os.Signal, 1)
		signal.Notify(sig, os.Interrupt, syscall.SIGTERM)

		<-sig
		log.Info().Msg("main received shutdown signal")
		cancel() // trigger shutdown of everything else
		
		echoCancel() // trigger shutdown echo
	}()

	flag.Parse()
	log.Setup(core.AppConfig.Name, core.Service, core.AppConfig.LogFile, core.AppConfig.LogJson, core.AppConfig.LokiServer, core.AppConfig.LokiKey, core.AppConfig.LokiLabels, core.AppConfig.LokiBuffersize, core.AppConfig.LokiMaxDelay, core.AppConfig.Debug)

	// init Opentelemetry
	if core.AppConfig.Tracing {
		tp, err := tracing.InitTracer()
		if err != nil {
			log.Fatal().Err(err).Msg("Initializing tracer failed")
		}
		defer func() {
			if err := tp.Shutdown(context.Background()); err != nil {
				log.Warn().Err(err).Msg("Error shutting down tracer provider")
			}
		}()
	}
	db.InitDB()
	defer db.CloseDB()

	log.Info().Str("port", core.AppConfig.PortNb).Msg("Starting web service")

	// start echo server
	e := echo.New()
	e.Use(echoprometheus.NewMiddleware(core.AppConfig.Service)) // add middleware to gather metrics
	e.Use(middleware.CORSConfigFromEnv())                       // set custom cors config

	// custom main, start async so it can wait on shutdown signal for cleanup
	go mainSvc(ctx, e)

	// add middleware
	e.Use(middleware.LoggerHandler)
	// e.Use(otelecho.Middleware(core.AppConfig.Sid))
	// e.Use(middleware.PolicyHandler) // Policy Enforcement Point to check access

	e.GET("/metrics", echoprometheus.NewHandler()) // adds route to serve gathered metrics
	rest.NewHandler(e)

	// serve doc
	if core.AppConfig.ElementsDoc {
		log.Info().Msg("Enabled Elements documentation")
		e.FileFS("/doc", "web/doc/elements.html", embeddedFS)
	} else if core.AppConfig.RapidocDoc {
		log.Info().Msg("Enabled Rapidoc documentation")
		e.FileFS("/doc", "web/doc/rapidoc.html", embeddedFS)
	}

	e.FileFS("/./examples/antrag/antrag.yaml", "web/doc/./examples/antrag/antrag.yaml", embeddedFS)

	// serve default stylesheets and javascript files
	e.StaticFS("/css/", echo.MustSubFS(web.Css, "css"))
	e.StaticFS("/js/", echo.MustSubFS(web.Js, "js"))
	e.StaticFS("/images/", echo.MustSubFS(web.Images, "images"))
	e.StaticFS("/", echo.MustSubFS(web.Public, "public"))

	// Start echo server (with or without TLS)
	var echoErr error
	if core.AppConfig.CertPem != "" && core.AppConfig.KeyPem != "" {
		sc := echo.StartConfig{
			Address:   ":443",
			TLSConfig: &tls.Config{},
			// core.AppConfig.CertPem), core.AppConfig.KeyPem
		}
		log.Info().Msg("Starting echo server with TLS")
		echoErr = sc.Start(echoCtx, e)
	} else {
		log.Info().Msg("Found no TLS certificates, STARTING WITHOUT TLS")
		echoErr = e.Start(":" + core.AppConfig.PortNb)
	}

	// Log shutdown info
	switch echoErr {
	case nil:
		log.Info().Msg("Echo server stopped cleanly")
	case http.ErrServerClosed:
		log.Info().Msg("Echo server shutdown")
	default:
		log.Error().Err(echoErr).Msg("Echo server failed")
	}

	log.Info().Msg("main exited")
}
