// Don't edit this file, as it is generated by dredger
package entities

import (
	"fmt"

	"github.com/google/uuid"
)

type Store struct {
	Description   string    `json:"description" yaml:"description" xml:"description" form:"description"`
	Id            uuid.UUID `json:"id" yaml:"id" xml:"id" form:"id"`
	Name          string    `json:"name" yaml:"name" xml:"name" form:"name"`
	Size          int32     `json:"size" yaml:"size" xml:"size" form:"size"`
	Address       string    `json:"address" yaml:"address" xml:"address" form:"address"`
	AnnualRevenue float32   `json:"annual_revenue" yaml:"annual_revenue" xml:"annual_revenue" form:"annual_revenue"`
}

func (v *Store) Validate() error {

	if v.Description == "" {
		return fmt.Errorf("Missing fieldDescription")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Description) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "description")
	}

	if v.Name == "" {
		return fmt.Errorf("Missing fieldName")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Name) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "name")
	}

	if v.Address == "" {
		return fmt.Errorf("Missing fieldAddress")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Address) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "address")
	}

	return nil
}
