// Don't edit this file, as it is generated by dredger
package middleware

import (
	"net/http"
	"os"
	"strconv"
	"strings"

	"antragservice6/core/log"

	"github.com/labstack/echo/v5"
	"github.com/labstack/echo/v5/middleware"
)

func CORSConfigFromEnv() echo.MiddlewareFunc {
	envOrigins := strings.TrimSpace(os.Getenv("ANTRAGSERVICE6_CORS_ALLOWED_ORIGINS"))
	credentialsEnv := strings.TrimSpace(os.Getenv("ANTRAGSERVICE6_CORS_ALLOW_CREDENTIALS"))

	var origins []string
	containsWildcard := false
	// Get all allowed origins
	for o := range strings.SplitSeq(envOrigins, ",") {
		o = strings.TrimSpace(o)
		if o != "" {
			origins = append(origins, o)
			if o == "*" {
				containsWildcard = true
			}
		}
	}

	// DEFAULT: allow all origins
	if len(origins) == 0 {
		origins = []string{"*"}
		log.Warn().Msg("Defaulting AllowOrigin:\"*\"")
		containsWildcard = true
	}

	// Parse credentials flag
	allowCredentials := false
	if credentialsEnv != "" {
		parsed, err := strconv.ParseBool(credentialsEnv)
		if err != nil {
			log.Debug().Str("value", credentialsEnv).Msg("Invalid CORS_ALLOW_CREDENTIALS value, should be 'true' or 'false' (defaulting to false)")
		} else {
			allowCredentials = parsed
		}
	}

	// Safety check
	if allowCredentials && containsWildcard {
		log.Warn().Msg("Invalid CORS config: AllowCredentials=true requires explicit origins")
	}

	// Construct CORS config
	return middleware.CORSWithConfig(middleware.CORSConfig{
		AllowOrigins: origins,
		AllowMethods: []string{
			http.MethodGet,
			http.MethodPost,
			http.MethodPut,
			http.MethodDelete,
			http.MethodPatch,
			http.MethodOptions,
		},
		AllowHeaders: []string{
			echo.HeaderOrigin,
			echo.HeaderContentType,
			echo.HeaderAccept,
			echo.HeaderAuthorization,
		},
		AllowCredentials: allowCredentials, // if true DO NOT USE allow origin: *
	})

}
