// Don't edit this file, as it is generated by dredger
package rest

import (
	"bytes"
	"encoding/base64"
	"image/png"
	"net/http"

	"bafoegservice/web/pages"

	"github.com/labstack/echo/v5"
	"github.com/pquerna/otp/totp"
	"golang.org/x/crypto/bcrypt"
)

var userStore = map[string]struct {
	PasswordHash string
	TOTPSecret   string
}{}

func RegisterHandler(c *echo.Context) error {
	if (*c).Request().Method == http.MethodGet {
		return Render(c, http.StatusOK, pages.RegisterForm())
	}

	email := (*c).FormValue("email")
	password := (*c).FormValue("password")

	hash, _ := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	key, _ := totp.Generate(totp.GenerateOpts{
		Issuer:      "Portal",
		AccountName: email,
	})

	img, _ := key.Image(200, 200)
	var buf bytes.Buffer
	png.Encode(&buf, img)
	qrCode := base64.StdEncoding.EncodeToString(buf.Bytes())

	session, _ := getSession(c)
	session.Values["pending_email"] = email
	session.Values["pending_password"] = string(hash)
	session.Values["pending_secret"] = key.Secret()
	session.Save((*c).Request(), (*c).Response())

	return Render(c, http.StatusOK, pages.TOTPSetup(qrCode))
}

func RegisterVerifyHandler(c *echo.Context) error {
	session, _ := getSession(c)
	secret, ok := session.Values["pending_secret"].(string)
	if !ok || secret == "" {
		return (*c).HTML(http.StatusBadRequest,
			`<div class="alert alert-danger">Session abgelaufen. Bitte neu registrieren.</div>`)
	}

	if !totp.Validate((*c).FormValue("totp_code"), secret) {
		return (*c).HTML(http.StatusUnauthorized,
			`<div class="alert alert-danger">Ungültiger Code. Bitte erneut versuchen.</div>`)
	}

	email := session.Values["pending_email"].(string)
	userStore[email] = struct {
		PasswordHash string
		TOTPSecret   string
	}{
		PasswordHash: session.Values["pending_password"].(string),
		TOTPSecret:   secret,
	}

	delete(session.Values, "pending_email")
	delete(session.Values, "pending_password")
	delete(session.Values, "pending_secret")
	session.Save((*c).Request(), (*c).Response())

	return (*c).HTML(http.StatusOK,
		`<div class="alert alert-success">Registriert! <a href="/auth/login">Einloggen</a></div>`)
}

func LoginHandler(c *echo.Context) error {
	if (*c).Request().Method == http.MethodGet {
		return Render(c, http.StatusOK, pages.LoginForm())
	}

	email := (*c).FormValue("email")
	password := (*c).FormValue("password")

	user, exists := userStore[email]
	if !exists || bcrypt.CompareHashAndPassword([]byte(user.PasswordHash), []byte(password)) != nil {
		return (*c).HTML(http.StatusUnauthorized,
			`<div class="alert alert-danger">Falsche Zugangsdaten.</div>`)
	}

	session, _ := getSession(c)
	session.Values["pending_login"] = email
	session.Save((*c).Request(), (*c).Response())

	(*c).Response().Header().Set("HX-Redirect", "/auth/login/totp")
	return (*c).NoContent(http.StatusOK)
}

func LoginTOTPHandler(c *echo.Context) error {
	if (*c).Request().Method == http.MethodGet {
		return Render(c, http.StatusOK, pages.TOTPVerify())
	}

	session, _ := getSession(c)
	email, ok := session.Values["pending_login"].(string)
	if !ok || email == "" {
		return (*c).HTML(http.StatusBadRequest,
			`<div class="alert alert-danger">Session abgelaufen. Bitte erneut einloggen.</div>`)
	}

	if !totp.Validate((*c).FormValue("totp_code"), userStore[email].TOTPSecret) {
		return (*c).HTML(http.StatusUnauthorized,
			`<div class="alert alert-danger">Ungültiger Code.</div>`)
	}

	delete(session.Values, "pending_login")
	session.Values["authenticated"] = true
	session.Values["user"] = email
	session.Save((*c).Request(), (*c).Response())

	(*c).Response().Header().Set("HX-Redirect", "/")
	return (*c).NoContent(http.StatusOK)
}

func LogoutHandler(c *echo.Context) error {
	session, _ := getSession(c)
	session.Values["authenticated"] = false
	delete(session.Values, "user")
	session.Save((*c).Request(), (*c).Response())

	(*c).Response().Header().Set("HX-Redirect", "/auth/login")
	return (*c).NoContent(http.StatusOK)
}
