// Don't edit this file, as it is generated by dredger
package entities

import (
	"fmt"
)

type Urlaubsantrag struct {
	Nachname    string `json:"nachname" yaml:"nachname" xml:"nachname" form:"nachname"`
	Startdatum  string `json:"startdatum" yaml:"startdatum" xml:"startdatum" form:"startdatum"`
	Urlaubsart  string `json:"urlaubsart" yaml:"urlaubsart" xml:"urlaubsart" form:"urlaubsart"`
	Vorname     string `json:"vorname" yaml:"vorname" xml:"vorname" form:"vorname"`
	Anhang      string `json:"anhang" yaml:"anhang" xml:"anhang" form:"anhang"`
	Begruendung string `json:"begruendung" yaml:"begruendung" xml:"begruendung" form:"begruendung"`
	Email       string `json:"email" yaml:"email" xml:"email" form:"email"`
	Enddatum    string `json:"enddatum" yaml:"enddatum" xml:"enddatum" form:"enddatum"`
}

func (v *Urlaubsantrag) Validate() error {

	if v.Nachname == "" {
		return fmt.Errorf("Missing fieldNachname")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Nachname) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "nachname")
	}

	if v.Startdatum == "" {
		return fmt.Errorf("Missing fieldStartdatum")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Startdatum) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "startdatum")
	}

	if v.Urlaubsart == "" {
		return fmt.Errorf("Missing fieldUrlaubsart")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Urlaubsart) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "urlaubsart")
	}

	if v.Vorname == "" {
		return fmt.Errorf("Missing fieldVorname")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Vorname) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "vorname")
	}

	if v.Anhang == "" {
		return fmt.Errorf("Missing fieldAnhang")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Anhang) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "anhang")
	}

	if v.Begruendung == "" {
		return fmt.Errorf("Missing fieldBegruendung")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Begruendung) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "begruendung")
	}

	if v.Email == "" {
		return fmt.Errorf("Missing fieldEmail")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Email) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "email")
	}

	if v.Enddatum == "" {
		return fmt.Errorf("Missing fieldEnddatum")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Enddatum) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "enddatum")
	}

	return nil
}
