openapi: "3.0.0"
info:
  title: Antrag
  version: "1.0.0"

paths:
  /antrag:
    get:
      operationId: getAntragForm
      summary: Antragsformular anzeigen
      responses:
        "200":
          description: Formular anzeigen
    post:
      operationId: createAntrag
      summary: Antrag einreichen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Antrag"
      responses:
        "201":
          description: Antrag erstellt

components:
  schemas:
    Antrag:
      type: object
      x-label: "form"
      properties:
        vorname:
          type: string
          x-ui-control: "input"
          x-ui-required: true
          x-ui-group: "personal"
        nachname:
          type: string
          x-ui-control: "input"
          x-ui-required: true
          x-ui-group: "personal"
        email:
          type: string
          x-ui-control: "input"
          x-ui-required: true
        begruendung:
          type: string
          x-ui-control: "textarea"
        dokument:
          type: string
          x-ui-control: "file"