// Don't edit this file, as it is generated by dredger
package entities

import (
	"fmt"
)

type Baumfaellung struct {
	Eigentuemer             string  `json:"eigentuemer" yaml:"eigentuemer" xml:"eigentuemer" form:"eigentuemer"`
	Gesundheitszustand      string  `json:"gesundheitszustand" yaml:"gesundheitszustand" xml:"gesundheitszustand" form:"gesundheitszustand"`
	Antragstellerrolle      string  `json:"antragstellerrolle" yaml:"antragstellerrolle" xml:"antragstellerrolle" form:"antragstellerrolle"`
	Baumart                 string  `json:"baumart" yaml:"baumart" xml:"baumart" form:"baumart"`
	Flurstuecksnummer       string  `json:"flurstuecksnummer" yaml:"flurstuecksnummer" xml:"flurstuecksnummer" form:"flurstuecksnummer"`
	NachbarnInformiert      bool    `json:"nachbarn_informiert" yaml:"nachbarn_informiert" xml:"nachbarn_informiert" form:"nachbarn_informiert"`
	ErsatzpflanzungArt      string  `json:"ersatzpflanzung_art" yaml:"ersatzpflanzung_art" xml:"ersatzpflanzung_art" form:"ersatzpflanzung_art"`
	GeschaetztesAlter       int     `json:"geschaetztes_alter" yaml:"geschaetztes_alter" xml:"geschaetztes_alter" form:"geschaetztes_alter"`
	Grundstuecksadresse     string  `json:"grundstuecksadresse" yaml:"grundstuecksadresse" xml:"grundstuecksadresse" form:"grundstuecksadresse"`
	FotosBaum               string  `json:"fotos_baum" yaml:"fotos_baum" xml:"fotos_baum" form:"fotos_baum"`
	GeplantesDatum          string  `json:"geplantes_datum" yaml:"geplantes_datum" xml:"geplantes_datum" form:"geplantes_datum"`
	Gutachten               string  `json:"gutachten" yaml:"gutachten" xml:"gutachten" form:"gutachten"`
	RichtigkeitBestaetigung bool    `json:"richtigkeit_bestaetigung" yaml:"richtigkeit_bestaetigung" xml:"richtigkeit_bestaetigung" form:"richtigkeit_bestaetigung"`
	Telefon                 string  `json:"telefon" yaml:"telefon" xml:"telefon" form:"telefon"`
	DatenschutzZustimmung   bool    `json:"datenschutz_zustimmung" yaml:"datenschutz_zustimmung" xml:"datenschutz_zustimmung" form:"datenschutz_zustimmung"`
	Denkmalschutz           bool    `json:"denkmalschutz" yaml:"denkmalschutz" xml:"denkmalschutz" form:"denkmalschutz"`
	Wohnort                 string  `json:"wohnort" yaml:"wohnort" xml:"wohnort" form:"wohnort"`
	AnzahlBaeume            int     `json:"anzahl_baeume" yaml:"anzahl_baeume" xml:"anzahl_baeume" form:"anzahl_baeume"`
	BegruendungDetails      string  `json:"begruendung_details" yaml:"begruendung_details" xml:"begruendung_details" form:"begruendung_details"`
	Bemerkungen             string  `json:"bemerkungen" yaml:"bemerkungen" xml:"bemerkungen" form:"bemerkungen"`
	Grundstuecksart         string  `json:"grundstuecksart" yaml:"grundstuecksart" xml:"grundstuecksart" form:"grundstuecksart"`
	Lageplan                string  `json:"lageplan" yaml:"lageplan" xml:"lageplan" form:"lageplan"`
	Nachname                string  `json:"nachname" yaml:"nachname" xml:"nachname" form:"nachname"`
	Postleitzahl            string  `json:"postleitzahl" yaml:"postleitzahl" xml:"postleitzahl" form:"postleitzahl"`
	Standort                string  `json:"standort" yaml:"standort" xml:"standort" form:"standort"`
	Baumhoehe               float64 `json:"baumhoehe" yaml:"baumhoehe" xml:"baumhoehe" form:"baumhoehe"`
	ErsatzpflanzungGeplant  bool    `json:"ersatzpflanzung_geplant" yaml:"ersatzpflanzung_geplant" xml:"ersatzpflanzung_geplant" form:"ersatzpflanzung_geplant"`
	Massnahme               string  `json:"massnahme" yaml:"massnahme" xml:"massnahme" form:"massnahme"`
	StrasseHausnummer       string  `json:"strasse_hausnummer" yaml:"strasse_hausnummer" xml:"strasse_hausnummer" form:"strasse_hausnummer"`
	Vorname                 string  `json:"vorname" yaml:"vorname" xml:"vorname" form:"vorname"`
	Baumumfang              int     `json:"baumumfang" yaml:"baumumfang" xml:"baumumfang" form:"baumumfang"`
	Begruendung             string  `json:"begruendung" yaml:"begruendung" xml:"begruendung" form:"begruendung"`
	Eigentuemernachweis     string  `json:"eigentuemernachweis" yaml:"eigentuemernachweis" xml:"eigentuemernachweis" form:"eigentuemernachweis"`
	Email                   string  `json:"email" yaml:"email" xml:"email" form:"email"`
}

func (v *Baumfaellung) Validate() error {

	if v.Eigentuemer == "" {
		return fmt.Errorf("Missing fieldEigentuemer")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Eigentuemer) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "eigentuemer")
	}

	if v.Gesundheitszustand == "" {
		return fmt.Errorf("Missing fieldGesundheitszustand")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Gesundheitszustand) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "gesundheitszustand")
	}

	if v.Antragstellerrolle == "" {
		return fmt.Errorf("Missing fieldAntragstellerrolle")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Antragstellerrolle) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "antragstellerrolle")
	}

	if v.Baumart == "" {
		return fmt.Errorf("Missing fieldBaumart")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Baumart) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "baumart")
	}

	if v.Flurstuecksnummer == "" {
		return fmt.Errorf("Missing fieldFlurstuecksnummer")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Flurstuecksnummer) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "flurstuecksnummer")
	}

	if v.ErsatzpflanzungArt == "" {
		return fmt.Errorf("Missing fieldErsatzpflanzungArt")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.ErsatzpflanzungArt) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "ersatzpflanzung_art")
	}

	if v.Grundstuecksadresse == "" {
		return fmt.Errorf("Missing fieldGrundstuecksadresse")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Grundstuecksadresse) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "grundstuecksadresse")
	}

	if v.FotosBaum == "" {
		return fmt.Errorf("Missing fieldFotosBaum")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.FotosBaum) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "fotos_baum")
	}

	if v.GeplantesDatum == "" {
		return fmt.Errorf("Missing fieldGeplantesDatum")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.GeplantesDatum) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "geplantes_datum")
	}

	if v.Gutachten == "" {
		return fmt.Errorf("Missing fieldGutachten")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Gutachten) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "gutachten")
	}

	if v.Telefon == "" {
		return fmt.Errorf("Missing fieldTelefon")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Telefon) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "telefon")
	}

	if v.Wohnort == "" {
		return fmt.Errorf("Missing fieldWohnort")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Wohnort) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "wohnort")
	}

	if v.BegruendungDetails == "" {
		return fmt.Errorf("Missing fieldBegruendungDetails")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.BegruendungDetails) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "begruendung_details")
	}

	if v.Bemerkungen == "" {
		return fmt.Errorf("Missing fieldBemerkungen")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Bemerkungen) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "bemerkungen")
	}

	if v.Grundstuecksart == "" {
		return fmt.Errorf("Missing fieldGrundstuecksart")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Grundstuecksart) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "grundstuecksart")
	}

	if v.Lageplan == "" {
		return fmt.Errorf("Missing fieldLageplan")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Lageplan) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "lageplan")
	}

	if v.Nachname == "" {
		return fmt.Errorf("Missing fieldNachname")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Nachname) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "nachname")
	}

	if v.Postleitzahl == "" {
		return fmt.Errorf("Missing fieldPostleitzahl")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Postleitzahl) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "postleitzahl")
	}

	if v.Standort == "" {
		return fmt.Errorf("Missing fieldStandort")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Standort) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "standort")
	}

	if v.Massnahme == "" {
		return fmt.Errorf("Missing fieldMassnahme")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Massnahme) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "massnahme")
	}

	if v.StrasseHausnummer == "" {
		return fmt.Errorf("Missing fieldStrasseHausnummer")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.StrasseHausnummer) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "strasse_hausnummer")
	}

	if v.Vorname == "" {
		return fmt.Errorf("Missing fieldVorname")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Vorname) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "vorname")
	}

	if v.Begruendung == "" {
		return fmt.Errorf("Missing fieldBegruendung")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Begruendung) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "begruendung")
	}

	if v.Eigentuemernachweis == "" {
		return fmt.Errorf("Missing fieldEigentuemernachweis")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Eigentuemernachweis) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "eigentuemernachweis")
	}

	if v.Email == "" {
		return fmt.Errorf("Missing fieldEmail")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Email) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "email")
	}

	return nil
}
