// Don't edit this file, as it is generated by dredger
package entities

import (
	"fmt"
)

type Bafoeg struct {
	KrankenversicherungKosten     float64 `json:"krankenversicherung_kosten" yaml:"krankenversicherung_kosten" xml:"krankenversicherung_kosten" form:"krankenversicherung_kosten"`
	StudiengangAusbildung         string  `json:"studiengang_ausbildung" yaml:"studiengang_ausbildung" xml:"studiengang_ausbildung" form:"studiengang_ausbildung"`
	ElternVerheiratet             bool    `json:"eltern_verheiratet" yaml:"eltern_verheiratet" xml:"eltern_verheiratet" form:"eltern_verheiratet"`
	Krankenversicherungsnachweis  string  `json:"krankenversicherungsnachweis" yaml:"krankenversicherungsnachweis" xml:"krankenversicherungsnachweis" form:"krankenversicherungsnachweis"`
	Studienform                   string  `json:"studienform" yaml:"studienform" xml:"studienform" form:"studienform"`
	Immatrikulationsbescheinigung string  `json:"immatrikulationsbescheinigung" yaml:"immatrikulationsbescheinigung" xml:"immatrikulationsbescheinigung" form:"immatrikulationsbescheinigung"`
	Ausbildungsart                string  `json:"ausbildungsart" yaml:"ausbildungsart" xml:"ausbildungsart" form:"ausbildungsart"`
	Bemerkungen                   string  `json:"bemerkungen" yaml:"bemerkungen" xml:"bemerkungen" form:"bemerkungen"`
	FoerderungszeitraumBis        string  `json:"foerderungszeitraum_bis" yaml:"foerderungszeitraum_bis" xml:"foerderungszeitraum_bis" form:"foerderungszeitraum_bis"`
	EigenesVermoegen              float64 `json:"eigenes_vermoegen" yaml:"eigenes_vermoegen" xml:"eigenes_vermoegen" form:"eigenes_vermoegen"`
	VornameVater                  string  `json:"vorname_vater" yaml:"vorname_vater" xml:"vorname_vater" form:"vorname_vater"`
	BerufVater                    string  `json:"beruf_vater" yaml:"beruf_vater" xml:"beruf_vater" form:"beruf_vater"`
	EigenesEinkommen              float64 `json:"eigenes_einkommen" yaml:"eigenes_einkommen" xml:"eigenes_einkommen" form:"eigenes_einkommen"`
	FoerderungBisher              bool    `json:"foerderung_bisher" yaml:"foerderung_bisher" xml:"foerderung_bisher" form:"foerderung_bisher"`
	Behinderung                   bool    `json:"behinderung" yaml:"behinderung" xml:"behinderung" form:"behinderung"`
	Rentenversicherungsnummer     string  `json:"rentenversicherungsnummer" yaml:"rentenversicherungsnummer" xml:"rentenversicherungsnummer" form:"rentenversicherungsnummer"`
	VoraussichtlichesEnde         string  `json:"voraussichtliches_ende" yaml:"voraussichtliches_ende" xml:"voraussichtliches_ende" form:"voraussichtliches_ende"`
	Email                         string  `json:"email" yaml:"email" xml:"email" form:"email"`
	Geburtsland                   string  `json:"geburtsland" yaml:"geburtsland" xml:"geburtsland" form:"geburtsland"`
	Ausbildungsstaette            string  `json:"ausbildungsstaette" yaml:"ausbildungsstaette" xml:"ausbildungsstaette" form:"ausbildungsstaette"`
	NachnameMutter                string  `json:"nachname_mutter" yaml:"nachname_mutter" xml:"nachname_mutter" form:"nachname_mutter"`
	Wohnsituation                 string  `json:"wohnsituation" yaml:"wohnsituation" xml:"wohnsituation" form:"wohnsituation"`
	EinkommensnachweisEltern      string  `json:"einkommensnachweis_eltern" yaml:"einkommensnachweis_eltern" xml:"einkommensnachweis_eltern" form:"einkommensnachweis_eltern"`
	Familienstand                 string  `json:"familienstand" yaml:"familienstand" xml:"familienstand" form:"familienstand"`
	EinkommenMutter               float64 `json:"einkommen_mutter" yaml:"einkommen_mutter" xml:"einkommen_mutter" form:"einkommen_mutter"`
	Wohnort                       string  `json:"wohnort" yaml:"wohnort" xml:"wohnort" form:"wohnort"`
	Personalausweis               string  `json:"personalausweis" yaml:"personalausweis" xml:"personalausweis" form:"personalausweis"`
	Postleitzahl                  string  `json:"postleitzahl" yaml:"postleitzahl" xml:"postleitzahl" form:"postleitzahl"`
	EinkommenVater                float64 `json:"einkommen_vater" yaml:"einkommen_vater" xml:"einkommen_vater" form:"einkommen_vater"`
	Fachsemester                  int     `json:"fachsemester" yaml:"fachsemester" xml:"fachsemester" form:"fachsemester"`
	NachnameVater                 string  `json:"nachname_vater" yaml:"nachname_vater" xml:"nachname_vater" form:"nachname_vater"`
	Auslandsaufenthalt            bool    `json:"auslandsaufenthalt" yaml:"auslandsaufenthalt" xml:"auslandsaufenthalt" form:"auslandsaufenthalt"`
	Telefon                       string  `json:"telefon" yaml:"telefon" xml:"telefon" form:"telefon"`
	Geburtsdatum                  string  `json:"geburtsdatum" yaml:"geburtsdatum" xml:"geburtsdatum" form:"geburtsdatum"`
	Geburtsort                    string  `json:"geburtsort" yaml:"geburtsort" xml:"geburtsort" form:"geburtsort"`
	Kontoauszug                   string  `json:"kontoauszug" yaml:"kontoauszug" xml:"kontoauszug" form:"kontoauszug"`
	Staatsangehoerigkeit          string  `json:"staatsangehoerigkeit" yaml:"staatsangehoerigkeit" xml:"staatsangehoerigkeit" form:"staatsangehoerigkeit"`
	Stipendium                    bool    `json:"stipendium" yaml:"stipendium" xml:"stipendium" form:"stipendium"`
	Nachname                      string  `json:"nachname" yaml:"nachname" xml:"nachname" form:"nachname"`
	FoerderungszeitraumVon        string  `json:"foerderungszeitraum_von" yaml:"foerderungszeitraum_von" xml:"foerderungszeitraum_von" form:"foerderungszeitraum_von"`
	DatenschutzZustimmung         bool    `json:"datenschutz_zustimmung" yaml:"datenschutz_zustimmung" xml:"datenschutz_zustimmung" form:"datenschutz_zustimmung"`
	BerufMutter                   string  `json:"beruf_mutter" yaml:"beruf_mutter" xml:"beruf_mutter" form:"beruf_mutter"`
	MieteMonatlich                float64 `json:"miete_monatlich" yaml:"miete_monatlich" xml:"miete_monatlich" form:"miete_monatlich"`
	VornameMutter                 string  `json:"vorname_mutter" yaml:"vorname_mutter" xml:"vorname_mutter" form:"vorname_mutter"`
	BeginnAusbildung              string  `json:"beginn_ausbildung" yaml:"beginn_ausbildung" xml:"beginn_ausbildung" form:"beginn_ausbildung"`
	Vorname                       string  `json:"vorname" yaml:"vorname" xml:"vorname" form:"vorname"`
	OrtAusbildungsstaette         string  `json:"ort_ausbildungsstaette" yaml:"ort_ausbildungsstaette" xml:"ort_ausbildungsstaette" form:"ort_ausbildungsstaette"`
	AnzahlGeschwister             int     `json:"anzahl_geschwister" yaml:"anzahl_geschwister" xml:"anzahl_geschwister" form:"anzahl_geschwister"`
	RichtigkeitBestaetigung       bool    `json:"richtigkeit_bestaetigung" yaml:"richtigkeit_bestaetigung" xml:"richtigkeit_bestaetigung" form:"richtigkeit_bestaetigung"`
	StrasseHausnummer             string  `json:"strasse_hausnummer" yaml:"strasse_hausnummer" xml:"strasse_hausnummer" form:"strasse_hausnummer"`
	Regelstudienzeit              int     `json:"regelstudienzeit" yaml:"regelstudienzeit" xml:"regelstudienzeit" form:"regelstudienzeit"`
	StipendiumBetrag              float64 `json:"stipendium_betrag" yaml:"stipendium_betrag" xml:"stipendium_betrag" form:"stipendium_betrag"`
	Krankenversicherung           string  `json:"krankenversicherung" yaml:"krankenversicherung" xml:"krankenversicherung" form:"krankenversicherung"`
	Mietvertrag                   string  `json:"mietvertrag" yaml:"mietvertrag" xml:"mietvertrag" form:"mietvertrag"`
}

func (v *Bafoeg) Validate() error {

	if v.StudiengangAusbildung == "" {
		return fmt.Errorf("Missing fieldStudiengangAusbildung")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.StudiengangAusbildung) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "studiengang_ausbildung")
	}

	if v.Krankenversicherungsnachweis == "" {
		return fmt.Errorf("Missing fieldKrankenversicherungsnachweis")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Krankenversicherungsnachweis) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "krankenversicherungsnachweis")
	}

	if v.Studienform == "" {
		return fmt.Errorf("Missing fieldStudienform")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Studienform) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "studienform")
	}

	if v.Immatrikulationsbescheinigung == "" {
		return fmt.Errorf("Missing fieldImmatrikulationsbescheinigung")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Immatrikulationsbescheinigung) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "immatrikulationsbescheinigung")
	}

	if v.Ausbildungsart == "" {
		return fmt.Errorf("Missing fieldAusbildungsart")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Ausbildungsart) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "ausbildungsart")
	}

	if v.Bemerkungen == "" {
		return fmt.Errorf("Missing fieldBemerkungen")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Bemerkungen) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "bemerkungen")
	}

	if v.FoerderungszeitraumBis == "" {
		return fmt.Errorf("Missing fieldFoerderungszeitraumBis")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.FoerderungszeitraumBis) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "foerderungszeitraum_bis")
	}

	if v.VornameVater == "" {
		return fmt.Errorf("Missing fieldVornameVater")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.VornameVater) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "vorname_vater")
	}

	if v.BerufVater == "" {
		return fmt.Errorf("Missing fieldBerufVater")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.BerufVater) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "beruf_vater")
	}

	if v.Rentenversicherungsnummer == "" {
		return fmt.Errorf("Missing fieldRentenversicherungsnummer")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Rentenversicherungsnummer) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "rentenversicherungsnummer")
	}

	if v.VoraussichtlichesEnde == "" {
		return fmt.Errorf("Missing fieldVoraussichtlichesEnde")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.VoraussichtlichesEnde) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "voraussichtliches_ende")
	}

	if v.Email == "" {
		return fmt.Errorf("Missing fieldEmail")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Email) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "email")
	}

	if v.Geburtsland == "" {
		return fmt.Errorf("Missing fieldGeburtsland")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Geburtsland) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "geburtsland")
	}

	if v.Ausbildungsstaette == "" {
		return fmt.Errorf("Missing fieldAusbildungsstaette")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Ausbildungsstaette) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "ausbildungsstaette")
	}

	if v.NachnameMutter == "" {
		return fmt.Errorf("Missing fieldNachnameMutter")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.NachnameMutter) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "nachname_mutter")
	}

	if v.Wohnsituation == "" {
		return fmt.Errorf("Missing fieldWohnsituation")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Wohnsituation) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "wohnsituation")
	}

	if v.EinkommensnachweisEltern == "" {
		return fmt.Errorf("Missing fieldEinkommensnachweisEltern")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.EinkommensnachweisEltern) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "einkommensnachweis_eltern")
	}

	if v.Familienstand == "" {
		return fmt.Errorf("Missing fieldFamilienstand")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Familienstand) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "familienstand")
	}

	if v.Wohnort == "" {
		return fmt.Errorf("Missing fieldWohnort")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Wohnort) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "wohnort")
	}

	if v.Personalausweis == "" {
		return fmt.Errorf("Missing fieldPersonalausweis")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Personalausweis) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "personalausweis")
	}

	if v.Postleitzahl == "" {
		return fmt.Errorf("Missing fieldPostleitzahl")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Postleitzahl) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "postleitzahl")
	}

	if v.NachnameVater == "" {
		return fmt.Errorf("Missing fieldNachnameVater")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.NachnameVater) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "nachname_vater")
	}

	if v.Telefon == "" {
		return fmt.Errorf("Missing fieldTelefon")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Telefon) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "telefon")
	}

	if v.Geburtsdatum == "" {
		return fmt.Errorf("Missing fieldGeburtsdatum")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Geburtsdatum) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "geburtsdatum")
	}

	if v.Geburtsort == "" {
		return fmt.Errorf("Missing fieldGeburtsort")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Geburtsort) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "geburtsort")
	}

	if v.Kontoauszug == "" {
		return fmt.Errorf("Missing fieldKontoauszug")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Kontoauszug) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "kontoauszug")
	}

	if v.Staatsangehoerigkeit == "" {
		return fmt.Errorf("Missing fieldStaatsangehoerigkeit")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Staatsangehoerigkeit) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "staatsangehoerigkeit")
	}

	if v.Nachname == "" {
		return fmt.Errorf("Missing fieldNachname")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Nachname) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "nachname")
	}

	if v.FoerderungszeitraumVon == "" {
		return fmt.Errorf("Missing fieldFoerderungszeitraumVon")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.FoerderungszeitraumVon) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "foerderungszeitraum_von")
	}

	if v.BerufMutter == "" {
		return fmt.Errorf("Missing fieldBerufMutter")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.BerufMutter) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "beruf_mutter")
	}

	if v.VornameMutter == "" {
		return fmt.Errorf("Missing fieldVornameMutter")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.VornameMutter) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "vorname_mutter")
	}

	if v.BeginnAusbildung == "" {
		return fmt.Errorf("Missing fieldBeginnAusbildung")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.BeginnAusbildung) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "beginn_ausbildung")
	}

	if v.Vorname == "" {
		return fmt.Errorf("Missing fieldVorname")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Vorname) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "vorname")
	}

	if v.OrtAusbildungsstaette == "" {
		return fmt.Errorf("Missing fieldOrtAusbildungsstaette")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.OrtAusbildungsstaette) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "ort_ausbildungsstaette")
	}

	if v.StrasseHausnummer == "" {
		return fmt.Errorf("Missing fieldStrasseHausnummer")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.StrasseHausnummer) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "strasse_hausnummer")
	}

	if v.Krankenversicherung == "" {
		return fmt.Errorf("Missing fieldKrankenversicherung")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Krankenversicherung) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "krankenversicherung")
	}

	if v.Mietvertrag == "" {
		return fmt.Errorf("Missing fieldMietvertrag")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Mietvertrag) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "mietvertrag")
	}

	return nil
}
