// Don't edit this file, as it is generated by dredger
package rest

import (
	"baumservice/core"

	"github.com/labstack/echo/v5"
	"github.com/r3labs/sse/v2"
)

func init() {
	core.SseServer = sse.New()
	core.SseServer.CreateStream("progress")
	core.SseServer.CreateStream("notice")
	core.HandleEvents = echo.WrapHandler(core.SseServer)
}
