// Don't edit this file, as it is generated by dredger
package rest

import (
	// "baumservice/rest/middleware"
	"baumservice/core"
	"baumservice/core/log"

	"github.com/google/uuid"
	"github.com/gorilla/sessions"
	"github.com/labstack/echo/v5"
)

var sessionStore *sessions.CookieStore

func init() {
	sessionStore = sessions.NewCookieStore([]byte(core.AppConfig.SessionKey))
}

func getSession(c *echo.Context) (*sessions.Session, error) {
	session, err := sessionStore.Get((*c).Request(), core.AppConfig.SessionKey)
	if err != nil || session.IsNew {
		id := uuid.Must(uuid.NewV7()).String()
		log.Info().Str("session", id).Msg("New session")
		session.Values["id"] = id
		//
		// set your default session state
		//
		err = session.Save((*c).Request(), (*c).Response())
		if err != nil {
			log.Error().Err(err).Msg("writing session store failed")
			return nil, err
		}
	}

	return session, nil
}

func NewHandler(e *echo.Echo) {
	g := e.Group("")

	// TODO: Make a validation with openAPI sense
	// 	spec, err := middleware.ParseOpenAPISpecFile("public/baum_v2.yaml", e.AcquireContext())
	// 	if err != nil {
	// 		e.Logger.Fatal(err)
	// 	}
	// 	g.Use(middleware.Validation(spec, e))
	//     e.HTTPErrorHandler = func(err error, c *echo.Context) {
	//         switch err := err.(type) {
	//         // in case ValidationError just send the message
	//         case middleware.ValidationError:
	//             (*c).String(err.Status, err.Message)
	//         // in all other cases use default behavior
	//         default:
	//             e.DefaultHTTPErrorHandler(err, c)
	//         }
	//     }

	// Operations for: "/"
	g.GET("/", GetRoot)

	// Operations for: "/baumfaellung"
	g.GET("/baumfaellung", GetBaumfaellungForm)
	// Operations for: "/baumfaellung"
	g.POST("/baumfaellung", CreateBaumfaellung)

	// Operations for: "/baumfaellung/:id"
	g.GET("/baumfaellung/:id", GetBaumfaellungById)
	// Operations for: "/baumfaellung/:id"
	g.DELETE("/baumfaellung/:id", DeleteBaumfaellungById)

	// Operations for: "/index.html"
	g.GET("/index.html", GetIndex)

	// Call handler extensions
	newHandlerExt(e)
}
