// Don't edit this file, as it is generated by dredger
package entities

import (
	"fmt"
)

type Antrag struct {
	Begruendung string `json:"begruendung" yaml:"begruendung" xml:"begruendung" form:"begruendung"`
	Dokument    string `json:"dokument" yaml:"dokument" xml:"dokument" form:"dokument"`
	Email       string `json:"email" yaml:"email" xml:"email" form:"email"`
	Nachname    string `json:"nachname" yaml:"nachname" xml:"nachname" form:"nachname"`
	Vorname     string `json:"vorname" yaml:"vorname" xml:"vorname" form:"vorname"`
}

func (v *Antrag) Validate() error {

	if v.Begruendung == "" {
		return fmt.Errorf("Missing fieldBegruendung")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Begruendung) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "begruendung")
	}

	if v.Dokument == "" {
		return fmt.Errorf("Missing fieldDokument")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Dokument) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "dokument")
	}

	if v.Email == "" {
		return fmt.Errorf("Missing fieldEmail")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Email) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "email")
	}

	if v.Nachname == "" {
		return fmt.Errorf("Missing fieldNachname")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Nachname) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "nachname")
	}

	if v.Vorname == "" {
		return fmt.Errorf("Missing fieldVorname")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Vorname) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "vorname")
	}

	return nil
}
