// Don't edit this file, as it is generated by dredger
package entities

import (
	"fmt"
)

type Baumfaellung struct {
	Vorname       string `json:"vorname" yaml:"vorname" xml:"vorname" form:"vorname"`
	Adresse       string `json:"adresse" yaml:"adresse" xml:"adresse" form:"adresse"`
	Begruendung   string `json:"begruendung" yaml:"begruendung" xml:"begruendung" form:"begruendung"`
	Dokument      string `json:"dokument" yaml:"dokument" xml:"dokument" form:"dokument"`
	Email         string `json:"email" yaml:"email" xml:"email" form:"email"`
	Massnahme     string `json:"massnahme" yaml:"massnahme" xml:"massnahme" form:"massnahme"`
	Standort      string `json:"standort" yaml:"standort" xml:"standort" form:"standort"`
	Baumart       string `json:"baumart" yaml:"baumart" xml:"baumart" form:"baumart"`
	Baumhoehe     float64 `json:"baumhoehe" yaml:"baumhoehe" xml:"baumhoehe" form:"baumhoehe"`
	Baumumfang    int    `json:"baumumfang" yaml:"baumumfang" xml:"baumumfang" form:"baumumfang"`
	Denkmalschutz bool   `json:"denkmalschutz" yaml:"denkmalschutz" xml:"denkmalschutz" form:"denkmalschutz"`
	Eigentuemer   string `json:"eigentuemer" yaml:"eigentuemer" xml:"eigentuemer" form:"eigentuemer"`
	Fotos         string `json:"fotos" yaml:"fotos" xml:"fotos" form:"fotos"`
	Nachname      string `json:"nachname" yaml:"nachname" xml:"nachname" form:"nachname"`
}

func (v *Baumfaellung) Validate() error {

	if v.Vorname == "" {
		return fmt.Errorf("Missing fieldVorname")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Vorname) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "vorname")
	}

	if v.Adresse == "" {
		return fmt.Errorf("Missing fieldAdresse")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Adresse) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "adresse")
	}

	if v.Begruendung == "" {
		return fmt.Errorf("Missing fieldBegruendung")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Begruendung) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "begruendung")
	}

	if v.Dokument == "" {
		return fmt.Errorf("Missing fieldDokument")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Dokument) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "dokument")
	}

	if v.Email == "" {
		return fmt.Errorf("Missing fieldEmail")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Email) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "email")
	}

	if v.Massnahme == "" {
		return fmt.Errorf("Missing fieldMassnahme")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Massnahme) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "massnahme")
	}

	if v.Standort == "" {
		return fmt.Errorf("Missing fieldStandort")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Standort) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "standort")
	}

	if v.Baumart == "" {
		return fmt.Errorf("Missing fieldBaumart")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Baumart) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "baumart")
	}

	if v.Eigentuemer == "" {
		return fmt.Errorf("Missing fieldEigentuemer")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Eigentuemer) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "eigentuemer")
	}

	if v.Fotos == "" {
		return fmt.Errorf("Missing fieldFotos")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Fotos) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "fotos")
	}

	if v.Nachname == "" {
		return fmt.Errorf("Missing fieldNachname")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Nachname) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "nachname")
	}

	return nil
}
