// Don't edit this file, as it is generated by dredger
package rest

import (
	"github.com/a-h/templ"
	echo "github.com/labstack/echo/v5"
)

// This custom Render replaces Echo's *echo.Context.Render() with templ's templ.Component.Render().
func Render(ctx *echo.Context, statusCode int, t templ.Component) error {
	(*ctx).Response().WriteHeader(statusCode)
	(*ctx).Response().Header().Set(echo.HeaderContentType, echo.MIMETextHTML)
	return t.Render((*ctx).Request().Context(), (*ctx).Response())
}
