// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string, serviceName string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/web/pages/layout.templ`, Line: 8, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " – OZG-Portal</title><link rel=\"stylesheet\" href=\"/css/bootstrap.min.css\"><link rel=\"stylesheet\" href=\"/css/bootstrap-icons.min.css\"><style>\n            .navbar-brand { font-weight: 600; }\n            .sidebar { min-height: calc(100vh - 56px); border-right: 1px solid #dee2e6; }\n            .sidebar .nav-link { color: #495057; border-radius: 6px; }\n            .sidebar .nav-link:hover { background-color: #f8f9fa; color: #0d6efd; }\n            .sidebar .nav-link.active { background-color: #e7f1ff; color: #0d6efd; font-weight: 500; }\n            .main-content { background-color: #f8f9fa; min-height: calc(100vh - 56px); }\n            footer { border-top: 1px solid #dee2e6; }\n        </style></head><body><!-- Navbar --><nav class=\"navbar navbar-expand-lg navbar-dark bg-primary\"><div class=\"container-fluid\"><a class=\"navbar-brand\" href=\"/\"><i class=\"bi bi-building me-2\"></i> OZG-Bürgerportal</a> <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\"><span class=\"navbar-toggler-icon\"></span></button><div class=\"collapse navbar-collapse\" id=\"navbarNav\"><ul class=\"navbar-nav me-auto\"><li class=\"nav-item\"><a class=\"nav-link\" href=\"/\"><i class=\"bi bi-house me-1\"></i>Start</a></li>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if serviceName != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<li class=\"nav-item\"><a class=\"nav-link active\" href=\"/{ serviceName }\"><i class=\"bi bi-file-earmark-text me-1\"></i>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/web/pages/layout.templ`, Line: 40, Col: 83}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"><i class=\"bi bi-list-ul me-1\"></i>Meine Anträge</a></li></ul><ul class=\"navbar-nav\"><li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"><i class=\"bi bi-person-circle me-1\"></i>Anmelden</a></li></ul></div></div></nav><!-- Inhalt --><div class=\"container-fluid\"><div class=\"row\"><!-- Sidebar --><div class=\"col-md-2 sidebar bg-white py-3 px-3\"><p class=\"text-muted small fw-bold mb-2\">NAVIGATION</p><ul class=\"nav flex-column gap-1\"><li class=\"nav-item\"><a class=\"nav-link\" href=\"/\"><i class=\"bi bi-house me-2\"></i>Startseite</a></li>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if serviceName != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<li class=\"nav-item\"><a class=\"nav-link active\" href=\"/{ serviceName }\"><i class=\"bi bi-file-earmark-text me-2\"></i>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/web/pages/layout.templ`, Line: 72, Col: 83}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"><i class=\"bi bi-clock-history me-2\"></i>Meine Anträge</a></li></ul><hr><p class=\"text-muted small fw-bold mb-2\">KONTO</p><ul class=\"nav flex-column gap-1\"><li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"><i class=\"bi bi-person me-2\"></i>Profil</a></li><li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"><i class=\"bi bi-shield-lock me-2\"></i>2FA / TOTP</a></li></ul></div><!-- Hauptinhalt --><div class=\"col-md-10 main-content py-4 px-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div></div></div><!-- Footer --><footer class=\"bg-white py-3 mt-auto\"><div class=\"container-fluid px-4\"><div class=\"d-flex justify-content-between align-items-center\"><span class=\"text-muted small\">OZG-Portal · Fraunhofer FOKUS · Gruppe 11 · 2026</span><div class=\"d-flex gap-3\"><a href=\"#\" class=\"text-muted small text-decoration-none\">Datenschutz</a> <a href=\"#\" class=\"text-muted small text-decoration-none\">Impressum</a> <a href=\"#\" class=\"text-muted small text-decoration-none\">Barrierefreiheit</a></div></div></div></footer><script src=\"/js/bootstrap.bundle.min.js\"></script><script src=\"/js/htmx.min.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
