// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func RegisterForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"row justify-content-center\"><div class=\"col-md-6\"><div class=\"card shadow-sm\"><div class=\"card-header bg-primary text-white\"><h4 class=\"mb-0\"><i class=\"bi bi-person-plus me-2\"></i>Registrierung</h4></div><div class=\"card-body\"><form hx-post=\"/auth/register\" hx-target=\"#result\" hx-swap=\"innerHTML\"><div class=\"mb-3\"><label for=\"email\" class=\"form-label fw-bold\">E-Mail<span class=\"text-danger\">*</span></label> <input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\" placeholder=\"beispiel@email.de\" required></div><div class=\"mb-3\"><label for=\"password\" class=\"form-label fw-bold\">Passwort<span class=\"text-danger\">*</span></label> <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" placeholder=\"Mindestens 8 Zeichen\" required></div><div class=\"mb-3\"><label for=\"password_confirm\" class=\"form-label fw-bold\">Passwort bestätigen<span class=\"text-danger\">*</span></label> <input type=\"password\" id=\"password_confirm\" name=\"password_confirm\" class=\"form-control\" placeholder=\"Passwort wiederholen\" required></div><div class=\"d-grid mt-4\"><button type=\"submit\" class=\"btn btn-primary btn-lg\"><i class=\"bi bi-arrow-right me-2\"></i>Weiter zur 2-Faktor-Einrichtung</button></div></form><div id=\"result\" class=\"mt-3\"></div><hr><p class=\"text-center text-muted\">Bereits registriert? <a href=\"/auth/login\">Hier einloggen</a></p></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Registrierung", "register").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
