// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020

package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AntragForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container mt-4\"><h1>Antrag</h1><form hx-post=\"/antrag\" hx-target=\"#result\" hx-swap=\"innerHTML\"><div class=\"mb-3 group-personal\"><label for=\"vorname\" class=\"form-label\">Vorname <span class=\"text-danger\">*</span></label> <input type=\"text\" id=\"vorname\" name=\"vorname\" class=\"form-control\" required></div><div class=\"mb-3 group-personal\"><label for=\"nachname\" class=\"form-label\">Nachname <span class=\"text-danger\">*</span></label> <input type=\"text\" id=\"nachname\" name=\"nachname\" class=\"form-control\" required></div><div class=\"mb-3\"><label for=\"email\" class=\"form-label\">Email <span class=\"text-danger\">*</span></label> <input type=\"text\" id=\"email\" name=\"email\" class=\"form-control\" required></div><div class=\"mb-3\"><label for=\"begruendung\" class=\"form-label\">Begruendung</label> <textarea id=\"begruendung\" name=\"begruendung\" class=\"form-control\"></textarea></div><div class=\"mb-3\"><label for=\"dokument\" class=\"form-label\">Dokument</label> <input type=\"file\" id=\"dokument\" name=\"dokument\" class=\"form-control\"></div><button type=\"submit\" class=\"btn btn-primary\">Absenden</button></form><div id=\"result\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
