# This workflow will publish the artifacts with goreleaser
name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.25
          cache: true
      - name: Set up tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/a-h/templ/cmd/templ@latest
      - name: Templ
        run: templ generate web/pages/*.templ
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: v1.25.0
          args: release --clean
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Generate SBOM
        uses: CycloneDX/gh-gomod-generate-sbom@v2
        with:
          version: v1
          args: mod -licenses -json -output sbom.json
      - name: Release SBOM
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sbom.json
